export const db = [
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
  {
    name: "drive",
    url: "https://image.tmdb.org/t/p/original//vVKlL4HyrQYAcJuaaUW49FrRqY5.jpg",
    details: " Movie ,10 ,3000 ,En ",
    category: "crime ,horror ,drama",
  },
];
